import {escapeHTML} from '../lib/caseLoader.js';
export function syntaxJSON(value){return escapeHTML(JSON.stringify(value,null,2).replace(/\[\s+(-?\d+(?:\.\d+)?),\s+(-?\d+(?:\.\d+)?)\s+\]/g,'[$1, $2]')).replace(/(&quot;.*?&quot;)(\s*:)?|\b(-?\d+(?:\.\d+)?)\b/g,(m,s,k,n)=>s?`<span class="${k?'json-key':'json-string'}">${s}</span>${k||''}`:`<span class="json-number">${n}</span>`);}
function syntaxFeature(f){const ids=new Set(f.topology.junctions.map(j=>j.id));return syntaxJSON(f).replace(/<span class="json-string">(&quot;([^&]+)&quot;)<\/span>/g,(whole,encoded,id)=>ids.has(id)?`<span class="json-string" data-junction-ref="${id}">${encoded}</span>`:whole);}
export class SVLViewer {
 constructor(el,onSelect,onHover,onEdit){this.el=el;this.onSelect=onSelect;this.onHover=onHover;this.onEdit=onEdit;el.addEventListener('click',e=>{const c=e.target.closest('[data-feature]');if(c)this.onSelect(c.dataset.feature,c.dataset.source);});el.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.dataset.feature){e.preventDefault();this.onSelect(e.target.dataset.feature,e.target.dataset.source);}});el.addEventListener('mouseover',e=>{const c=e.target.closest('[data-feature]');if(c)this.onHover(c.dataset.feature,c.dataset.source);});el.addEventListener('mouseleave',()=>this.onHover(null));}
 render(doc,raw,state){this.el.scrollTop=0;if(state.editing){const selected=doc.features.find(f=>f.id===state.selected)||doc.features[0];if(!selected){this.el.innerHTML='<div class="empty">No feature available to edit.</div>';return;}this.el.innerHTML='<textarea class="editor" aria-label="Edit selected SVL feature" spellcheck="false"></textarea>';const area=this.el.querySelector('textarea');area.value=JSON.stringify(selected,null,2);area.addEventListener('input',()=>this.onEdit(area.value,selected.id));return;}
 if(state.raw){this.el.innerHTML=raw.map(r=>`<article class="svl-card" data-feature="${escapeHTML(r.featureId)}" data-source="prediction" tabindex="0" role="button"><header><span>${escapeHTML(r.featureId)}</span><span>line ${r.line}</span></header><pre>${escapeHTML(r.predict)}</pre></article>`).join('');return;}
 this.el.innerHTML=doc.features.filter(f=>state.layers.has(f.class)).map(f=>`<article class="svl-card" data-feature="${escapeHTML(f.id)}" data-source="${state.codeSource}" tabindex="0" role="button"><header><span><span class="swatch" style="--layer:var(--${f.class})"></span> ${escapeHTML(f.id)}</span><span>${f.geometry.type}</span></header><pre>${syntaxFeature(f)}</pre></article>`).join('')||'<div class="empty">No visible features. Enable a layer.</div>';this.highlight(state.selected,false);}
 highlightJunction(id){this.el.querySelectorAll('[data-junction-ref]').forEach(e=>{e.classList.toggle('junction-reference',e.dataset.junctionRef===id);if(e.dataset.junctionRef===id)e.scrollIntoView({block:'nearest'});});}
 highlight(id,scroll=false){let scrolled=false;this.el.querySelectorAll('[data-feature]').forEach(e=>{e.classList.toggle('selected',e.dataset.feature===id);if(scroll&&!scrolled&&e.dataset.feature===id){e.scrollIntoView({block:'nearest',behavior:'auto'});scrolled=true;}});}
}
