import {classes,featurePoints,parseSVL,gtToSVL} from './lib/geometry.js';
import {StaticCaseProvider,escapeHTML,downloadFile} from './lib/caseLoader.js';
import {VectorViewer} from './components/VectorViewer.js';
import {SVLViewer} from './components/SVLViewer.js';
const $=s=>document.querySelector(s),provider=new StaticCaseProvider();let catalog=[],data,original,loadSequence=0;
const state={view:'prediction',imageMode:'overlay',layers:new Set(classes),vertices:false,topology:false,boxes:false,vectorBackground:false,selected:null,selectedSource:'prediction',hover:null,hoverSource:'prediction',junction:null,editing:false,raw:false,codeSource:'prediction',filter:'all',dirty:false};
function modal(title,body){$('#dialog-title').textContent=title;$('#dialog-body').textContent=body;$('#dialog').showModal();}
function toast(message){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.role='status';t.textContent=message;document.body.append(t);setTimeout(()=>t.remove(),3800);}
function status(text,error=false){$('#parse-status').textContent=text;$('#parse-status').classList.toggle('error',error);}
function hover(id,source='prediction'){if(state.editing)return;state.hover=id;state.hoverSource=source;left.highlight(id||state.selected,id?source:state.selectedSource,data,state);right.highlight(id||state.selected,id?source:state.selectedSource,data,state);code.highlight(id||state.selected);}
function selectFeature(id,source='prediction',junction=null){if(state.editing&&source==='gt'){toast('Close Edit SVL to inspect ground truth.');return;}state.selected=id;state.selectedSource=source;state.junction=junction;state.hover=null;if(state.codeSource!==source){state.codeSource=source;renderCode();}else if(state.editing)renderCode();left.highlight(id,source,data,state);right.highlight(id,source,data,state);code.highlight(id,true);if(junction)code.highlightJunction(junction);renderInfo();}
const left=new VectorViewer($('#image-map'),selectFeature,hover,box=>right.setCamera(box));
const right=new VectorViewer($('#vector-map'),selectFeature,hover,box=>left.setCamera(box));
const code=new SVLViewer($('#svl'),selectFeature,hover,(text,id)=>{
 try{const changed=JSON.parse(text);if(changed.id!==id)throw Error('Keep the feature ID unchanged to preserve correspondence.');const doc=structuredClone(data.svl),idx=doc.features.findIndex(f=>f.id===id);doc.features[idx]=changed;const parsed=parseSVL(JSON.stringify(doc));Object.assign(data,parsed);state.dirty=true;state.layers.add(changed.class);renderMaps();renderLayers();renderInfo();status('✓ Valid SVL · geometry updated · unsaved local edit');}catch(e){status(e.message,true);}
});
function renderMaps(){left.render(data,state,true);right.render(data,state,false);$('#topology-count').textContent=state.topology?`${data[state.view==='gt'?'gtTopology':'topology'].nodes.length} junctions · ${data.topology.mode==='stitched-graph'?'stitched graph':'local graph'}`:'Pixel coordinates';}
function renderCode(){const doc=state.codeSource==='gt'?gtToSVL(data.gt,data.gtTopology,data.metadata.coordinateSystem):data.svl;code.render(doc,data.raw,state);$('#raw').classList.toggle('active',state.raw);$('#normalized').classList.toggle('active',!state.raw);$('#edit').classList.toggle('active',state.editing);$('#edit').textContent=state.editing?'Done editing':'Edit SVL';if(!state.editing)status(state.raw?(data.metadata.roadStitching?'Original model output · before road stitching':'Original model output · normalized crop coordinates'):`${state.codeSource==='gt'?'Ground-truth':'Prediction'} SVL · image coordinates${state.dirty?' · edited locally':''}`);}
function renderLayers(){$('#layers').innerHTML=classes.map(c=>`<label style="--layer:var(--${c})"><input type="checkbox" data-layer="${c}" ${state.layers.has(c)?'checked':''}><span class="swatch"></span>${c[0].toUpperCase()+c.slice(1)}</label>`).join('');}
function renderInfo(){const f=data[state.selectedSource]?.features.find(f=>f.id===state.selected);const n=data[state.selectedSource==='gt'?'gtTopology':'topology'].nodes.find(n=>n.id===state.junction);$('#counts').textContent=`${data.prediction.features.length} features · ${data.topology.nodes.length} junctions`;
 if(n){$('#feature-info').innerHTML=`<strong>${escapeHTML(n.id)}</strong><span>Degree ${n.degree}</span><span>${state.selectedSource} · ${data.topology.mode==='stitched-graph'?'stitched graph':'local incidence'}</span><br>Connected polylines: ${n.connectedPolylines.map(id=>`<button data-segment="${escapeHTML(id)}">${escapeHTML(id)}</button>`).join('')||'No connected polylines'}`;return;}
 if(!f){$('#feature-info').textContent='Select any shape, SVL feature, or junction to explore the correspondence.';return;}
 const polygon=f.geometry.type==='Polygon',count=polygon?f.geometry.coordinates.reduce((n,r)=>n+r.length-1,0):featurePoints(f).length;
 $('#feature-info').innerHTML=`<strong>${escapeHTML(f.id)}</strong><span>${f.properties.class}</span><span>${f.geometry.type}</span><span>${count} vertices</span>${polygon?`<span>${f.geometry.coordinates.length-1} interior rings</span>`:`<span>${f.geometry.coordinates.length} polylines</span>`}<span>${state.selectedSource}${state.dirty&&state.selectedSource==='prediction'?' · local edit':''}</span>`;
}
function caseCounts(m,compact=false){const c=m.counts;if(!c)return m.classes.join(' + ');return m.classes.map(k=>k==='road'?`${c.roadPolylines} ${compact?'lines':'road polylines'}`:`${c[k]} ${compact?(k==='building'?'bldg':'water'):(k==='building'?'buildings':'water regions')}`).join(' · ');}
function renderGallery(){const visible=catalog.filter(m=>state.filter==='all'||(state.filter==='multi-category'?m.mode===state.filter:m.mode==='single-category'&&m.classes.includes(state.filter)));$('#gallery').innerHTML=visible.map(m=>`<button class="case-card ${data?.metadata.id===m.id?'active':''}" data-case="${m.id}" aria-pressed="${data?.metadata.id===m.id}" title="${escapeHTML(m.description+' '+caseCounts(m))}"><img src="${provider.thumbnail(m.id)}" alt="${escapeHTML(m.dataset+' remote sensing scene')}" loading="lazy"><div class="card-text"><span class="badge">${m.dataset} · ${m.mode==='multi-category'?(m.selectionFocus&&m.selectionFocus!=='original'?(m.selectionFocus==='stitched'?'STITCHED':m.selectionFocus.replace('WaterBody','Water').toUpperCase()+'-RICH'):'UNIFIED'):'SINGLE'}</span><strong>${m.name}</strong><small>${caseCounts(m,true)}</small></div></button>`).join('');$('#case-total').textContent=`${visible.length===catalog.length?'':visible.length+' / '}${catalog.length} real-data scenes`;$('#case-jump').innerHTML='<option value="">Jump to scene…</option>'+visible.map(m=>`<option value="${m.id}">${m.dataset} · ${m.name}</option>`).join('');$('#case-jump').value=visible.some(m=>m.id===data?.metadata.id)?data.metadata.id:'';}
async function loadCase(id){const seq=++loadSequence;try{const result=await provider.load(id);if(seq!==loadSequence)return;data=result;original=structuredClone(result);Object.assign(state,{selected:null,hover:null,junction:null,editing:false,raw:false,dirty:false,codeSource:state.view==='gt'?'gt':'prediction',selectedSource:state.view==='gt'?'gt':'prediction'});left.box=null;right.box=null;$('#case-title').innerHTML=`${escapeHTML(data.metadata.name)} <small>${caseCounts(data.metadata)} · ${data.metadata.dataset}</small>`;$('#dataset').textContent=data.metadata.dataset;$('#dimensions').textContent=`${data.metadata.width} × ${data.metadata.height} px`;$('#boxes').disabled=!!data.detections.unavailableReason;$('#boxes').title=data.detections.unavailableReason||'Independent detection predictions';if($('#boxes').disabled){state.boxes=false;$('#boxes').checked=false;}renderGallery();renderLayers();renderMaps();renderCode();renderInfo();history.replaceState(null,'','#'+id);}catch(e){modal('Unable to load case',e.message);}}
$('#case-jump').onchange=e=>{if(e.target.value)loadCase(e.target.value);};
for(const [id,direction] of [['gallery-prev',-1],['gallery-next',1]])$('#'+id).onclick=()=>$('#gallery').scrollBy({left:direction*$('#gallery').clientWidth*.75,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
$('#gallery').onclick=e=>{const b=e.target.closest('[data-case]');if(b)loadCase(b.dataset.case);};
$('#filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;$('#filters').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderGallery();};
$('#layers').onchange=e=>{const c=e.target.dataset.layer;if(c){e.target.checked?state.layers.add(c):state.layers.delete(c);renderMaps();renderCode();}};
$('#view').onchange=e=>{state.view=e.target.value;state.imageMode=state.view==='prediction'?'overlay':state.view;state.codeSource=state.view==='gt'?'gt':'prediction';state.selectedSource=state.codeSource;state.selected=null;state.junction=null;state.editing=false;state.raw=false;syncImageTabs();renderMaps();renderCode();renderInfo();};
function syncImageTabs(){$('#image-tabs').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.image===state.imageMode));}
$('#image-tabs').onclick=e=>{if(e.target.dataset.image){state.imageMode=e.target.dataset.image;syncImageTabs();renderMaps();}};
for(const key of ['vertices','topology','boxes'])$('#'+key).onchange=e=>{state[key]=e.target.checked;renderMaps();};
$('#vector-bg').onclick=()=>{state.vectorBackground=!state.vectorBackground;$('#vector-bg').classList.toggle('active',state.vectorBackground);renderMaps();};
$('#raw').onclick=()=>{state.raw=true;state.editing=false;state.codeSource='prediction';renderCode();};$('#normalized').onclick=()=>{state.raw=false;state.editing=false;renderCode();};
$('#edit').onclick=()=>{state.editing=!state.editing;state.raw=false;state.codeSource='prediction';state.selectedSource='prediction';if(state.editing){state.view='prediction';$('#view').value='prediction';state.imageMode='overlay';syncImageTabs();state.selected=data.prediction.features.find(f=>f.id===state.selected)?.id||data.prediction.features[0]?.id;state.junction=null;}renderMaps();renderCode();renderInfo();if(state.editing)status('Edit this feature · polygon rings must remain closed · updates as you type');};
$('#reset').onclick=()=>{data=structuredClone(original);state.dirty=false;state.editing=false;state.selected=null;state.junction=null;left.fit();renderMaps();renderCode();renderInfo();toast('Original predictions restored.');};
$('#download-svl').onclick=()=>downloadFile(`${data.metadata.id}-${state.raw?'raw':'map'}-svl.json`,state.raw?data.raw:state.codeSource==='gt'?gtToSVL(data.gt,data.gtTopology,data.metadata.coordinateSystem):data.svl);
$('#export').onclick=()=>{const src=state.view==='gt'?'gt':'prediction';downloadFile(`${data.metadata.id}-${src}${state.dirty&&src==='prediction'?'-edited':''}.geojson`,{...data[src],coordinateSystem:data.metadata.coordinateSystem,provenance:{dataset:data.metadata.dataset,source:data.metadata.source,locallyEdited:state.dirty&&src==='prediction',note:'Local image pixels, not WGS84 longitude/latitude. Georeferencing is required before geographic GIS overlay.'}});toast('Exported vector geometry in image pixel coordinates.');};
$('#provenance').onclick=()=>modal('Data & coordinate provenance',JSON.stringify({...data.metadata,topology:data.topology.provenance,detectionNote:data.detections.unavailableReason||'Bboxes are from a separate detection evaluation; no detector-to-vector cascade or one-to-one association is claimed.',rawSVL:'Raw output retains model predictions. Map SVL is a deterministic display adapter in image coordinates.',gt:data.metadata.gtDescription||'Ground truth is the evaluation label transformed using the same crop transform, not a fabricated match.',localEdits:state.dirty},null,2));
$('#help').onclick=()=>modal('Explore Image ↔ Language ↔ Vector','1. Start with an IRSAMap scene: buildings, roads, and water share one map.\n\n2. Hover or click a shape or an SVL feature. Both maps and the code selection stay linked. Scroll to zoom; drag to pan.\n\n3. Switch Prediction / Ground truth / Prediction + GT. GT has a purple dashed boundary. Enable Bboxes to inspect the separate detection run.\n\n4. Turn on Show topology and click a purple road junction to inspect its degree and connected polylines. Multicategory roads use the stitched region graph and its junction adjacency. Single-category roads retain patch-local predicted junctions.\n\n5. Select a feature and choose Edit SVL. Change a vertex, a compatible class (building ↔ water), or junction coordinates. Valid edits update the map immediately; incomplete JSON preserves the last valid map. Polygon rings must stay closed. Reset scene restores predictions.\n\n6. Export vectors downloads the current prediction (including edits), or GT in GT mode. Coordinates are local image pixels, not geographic coordinates. Raw output always preserves the original model text.\n\nAll cases use existing offline results. No model server or network is needed in the standalone HTML.');
$('#close-dialog').onclick=()=>$('#dialog').close();
$('.pipeline').onclick=e=>{const b=e.target.closest('[data-rep]');if(!b)return;$('.pipeline').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));const rep=b.dataset.rep;if(rep==='image'){state.imageMode='image';syncImageTabs();}if(rep==='topology'){state.topology=true;$('#topology').checked=true;state.layers.add('road');renderLayers();}if(rep==='vector'){state.imageMode='overlay';state.topology=false;$('#topology').checked=false;syncImageTabs();}if(rep==='svl'){$('#svl').scrollIntoView({block:'nearest'});state.raw=false;renderCode();}renderMaps();};
$('#feature-info').onclick=e=>{const id=e.target.dataset.segment;if(!id)return;const seg=data[state.selectedSource==='gt'?'gtTopology':'topology'].segments.find(s=>s.id===id);if(seg){for(const viewer of [left,right])viewer.element('path',{d:seg.coordinates.map((p,i)=>`${i?'L':'M'}${p[0]},${p[1]}`).join(' '),fill:'none',stroke:'var(--highlight)','stroke-width':5,class:'bound selection-box'});toast(id);}};
(async()=>{try{catalog=await provider.catalog();if(!catalog.length)throw Error('No cases have been prepared.');renderGallery();const id=location.hash.slice(1);await loadCase(catalog.some(m=>m.id===id)?id:catalog.find(m=>m.mode==='multi-category')?.id||catalog[0].id);}catch(e){modal('Demo setup',e.message+'\nRun npm run build and open dist/index.html.');}})();
